Repository rainbowdashlabs/reputation-bot, pull requests merged in 2021-07, with the labels that each got.

#91 Feature/improve gdpr data
  src/main/java/de/chojo/repbot/data/GdprData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/resources/database/1/patch_6.sql
Labels: enhancement

#94 Improve scan command
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
Labels: enhancement, size: small

#93 Initial implementation of prune command
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Prune.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/service/GdprService.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: feature, size: medium

#95 Release 1.2.5
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Prune.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/data/GdprData.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/service/GdprService.java
  src/main/resources/database/1/patch_6.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, feature

#96 Add new default thankwords
  src/main/resources/Thankswords.json
Labels: enhancement

#99 Feature/channel list type
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettingUpdate.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/resources/database/1/patch_3.sql
  src/main/resources/database/1/patch_4.sql
  src/main/resources/database/1/patch_7.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, feature

#98 Add a channel subcommand to add all visible channel
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/util/FilterUtil.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, feature

#101 Fix reaction reputation
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
Labels: bug

#100 Feature/multi reactions
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Reactions.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/resources/database/1/patch_8.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, feature

#97 Add new languages
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: enhancement

#103 Release 1.3.0
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Reactions.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettingUpdate.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/util/FilterUtil.java
  src/main/resources/Thankswords.json
  src/main/resources/database/1/patch_3.sql
  src/main/resources/database/1/patch_4.sql
  src/main/resources/database/1/patch_7.sql
  src/main/resources/database/1/patch_8.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: enhancement, feature

#106 Fix prune error on user id
  src/main/java/de/chojo/repbot/commands/Prune.java
Labels: bug

#108 Bugfixes
  src/main/java/de/chojo/repbot/commands/Reactions.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
Labels: bug

#115 Feature/error handling
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/util/PermissionErrorHandler.java
Labels: bug, enhancement

#104 Improve Dockerfile build
  docker/Dockerfile
  docker/docker-compose.yml
  docker/start.sh
Labels: enhancement

#112 Feature/guild dashboard
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Dashboard.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildReputationStats.java
  src/main/resources/database/1/patch_10.sql
  src/main/resources/database/version
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: feature, size: medium

#113 Feature/emoji debug
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/util/EmojiDebug.java
  src/main/resources/database/1/patch_10.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: feature

#114 Feature/donor receiver roles
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/util/StringUtil.java
  src/main/resources/database/1/patch_10.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: feature, size: large

#116 Release 1.4.0
  build.gradle.kts
  docker/Dockerfile
  docker/docker-compose.yml
  docker/start.sh
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Dashboard.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildReputationStats.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/util/EmojiDebug.java
  src/main/java/de/chojo/repbot/util/PermissionErrorHandler.java
  src/main/java/de/chojo/repbot/util/StringUtil.java
  src/main/resources/database/1/patch_10.sql
  src/main/resources/database/version
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: enhancement, feature, refactoring, size: large

#131 Fix table name in donor role removal query
  src/main/java/de/chojo/repbot/data/GuildData.java
Labels: bug, size: small

#130 Update locale codes
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/config/elements/Links.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: enhancement

#129 Add cooldown for reaction addition to avoid spaming
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
Labels: enhancement, size: small

#127 Fix/channel command
  src/main/java/de/chojo/repbot/commands/Channel.java
Labels: bug, size: small

#128 Add embed thank type
  src/main/java/de/chojo/repbot/analyzer/ThankType.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
Labels: bug, enhancement

#132 Feature/enhancements
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/util/EmojiDebug.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: enhancement

#133 Release 1.4.2
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/analyzer/ThankType.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/config/elements/Links.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/util/EmojiDebug.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: bug, enhancement, refactoring, size: medium

#135 Remove users in cleanup schedule from ranking list
  src/main/resources/database/1/patch_11.sql
  src/main/resources/database/version
Labels: enhancement, size: small

#136 Feature/botlist enhancements
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/config/elements/Botlist.java
  src/main/resources/database/1/patch_11.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: enhancement, feature

#140 Feature/enhance data logging
  build.gradle.kts
  src/main/java/de/chojo/repbot/data/GdprData.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/StatisticData.java
  src/main/java/de/chojo/repbot/data/VoiceData.java
Labels: enhancement

#139 Fix/bugfixes
  src/main/java/de/chojo/repbot/data/GdprData.java
  src/main/java/de/chojo/repbot/util/PermissionErrorHandler.java
Labels: bug

#141 Get rid of the DbUtil which is replaced by sql-utils
  build.gradle.kts
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/util/DbUtil.java
Labels: enhancement
