Repository rainbowdashlabs/reputation-bot, pull requests merged in 2021-05, with the labels that each got.

#24 Contribution
  CONTRIBUTING.md
Labels: documentation, enhancement

#20 Feature: Send fancy image sometimes
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/MagicImage.java
  src/main/java/de/chojo/repbot/manager/ReputationManager.java
Labels: enhancement

#30 config update
  docker/config/config.json
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/resources/config.json
Labels: enhancement

#33 Feature/reaction feeback
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement

#35 Feature/remove reputation by reaction
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement

#36 Add default thankwords
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/resources/Thankswords.json
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement

#37 Fix remove message. name was used instead of mention
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
Labels: bug

#34 fix wrong receiver in message log
  src/main/java/de/chojo/repbot/commands/Log.java
Labels: bug

#41 Avoid that new users are invalidated
  src/main/java/de/chojo/repbot/manager/MemberCacheManager.java
Labels: bug, enhancement

#44 Fix wrong order in request message embed
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/test/java/de/chojo/repbot/listener/MessageListenerTest.java
Labels: bug

#43 Use fake users and avoid user retrieval from api
  src/main/java/de/chojo/repbot/commands/Log.java
Labels: enhancement

#42 Make top list mobile friendly #40
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationUser.java
Labels: enhancement

#45 Release of 1.1.1
  build.gradle.kts
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationUser.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/manager/MemberCacheManager.java
  src/main/java/de/chojo/repbot/manager/ReputationManager.java
  src/main/java/de/chojo/repbot/util/HistoryUtil.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/test/java/de/chojo/repbot/listener/MessageListenerTest.java
Labels: bug, enhancement
