Repository rainbowdashlabs/reputation-bot, pull requests merged in 2021-09, with the labels that each got.

#153 Remove unused test
  src/test/java/de/chojo/repbot/listener/MessageListenerTest.java
Labels: size: small, prio: lowest

#152 Feature/bugfixes
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/util/Messages.java
  src/main/resources/database/1/patch_14.sql
  src/main/resources/database/version
Labels: bug

#154 Fix reputation spam via embed
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/listener/voting/VoteRequest.java
Labels: bug, size: small, prio: high

#156 Russian localisation prop
  src/main/resources/locale_ru_RU.properties
Labels: locale

#157 Russian thankswords
  src/main/resources/Thankswords.json
Labels: locale
