Repository rainbowdashlabs/reputation-bot, pull requests merged in 2021-06, with the labels that each got.

#47 Support slash commands
  build.gradle.kts
  docker/config/config.json
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/AnalyzerResult.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Help.java
  src/main/java/de/chojo/repbot/commands/Invite.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Source.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/Database.java
  src/main/java/de/chojo/repbot/config/elements/MagicImage.java
  src/main/java/de/chojo/repbot/config/elements/TestMode.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/updater/Patch.java
  src/main/java/de/chojo/repbot/data/updater/QueryReplacement.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/updater/VersionInfo.java
  src/main/java/de/chojo/repbot/data/util/DbUtil.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/java/de/chojo/repbot/data/wrapper/RemovalTask.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationLogEntry.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationRole.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationUser.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/java/de/chojo/repbot/listener/VoteRequest.java
  src/main/java/de/chojo/repbot/manager/MemberCacheManager.java
  src/main/java/de/chojo/repbot/manager/ReputationManager.java
  src/main/java/de/chojo/repbot/manager/RoleAssigner.java
  src/main/java/de/chojo/repbot/util/MessageUtil.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, size: very large

#50 Feature/query refactoring
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
Labels: size: medium

#52 Implement button confirmation dialog
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/listener/voting/VoteComponent.java
  src/main/java/de/chojo/repbot/listener/voting/VoteRequest.java
  src/main/java/de/chojo/repbot/manager/ReputationService.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, size: medium

#53 Fix member context
  src/main/java/de/chojo/repbot/util/HistoryUtil.java
Labels: bug, size: small

#59 Implement error message
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: size: small

#57 Feature/voice activitiy
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/data/VoiceData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/VoiceStateListener.java
  src/main/java/de/chojo/repbot/manager/ReputationService.java
  src/main/java/de/chojo/repbot/util/ContextResolver.java
  src/main/resources/database/1/patch_1.sql
  src/main/resources/database/1/setup.sql
  src/main/resources/log4j2.xml
Labels: enhancement, size: medium

#58 Refactoring and Documentation
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettingUpdate.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
Labels: enhancement, size: small

#62 Feature/better context
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettingUpdate.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettings.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/manager/ReputationService.java
  src/main/resources/database/1/patch_1.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement

#63 Add profile badges
  docker/config/config.json
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/Badges.java
Labels: enhancement

#64 Improve logging and add webhook logging
  build.gradle.kts
  docker/config/log4j2.xml
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Help.java
  src/main/java/de/chojo/repbot/listener/LogListener.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/java/de/chojo/repbot/util/DiscordWebhookAppender.java
  src/main/java/de/chojo/repbot/util/LogNotify.java
  src/main/resources/log4j2.xml
Labels: enhancement

#65 Feature/prep release 1.2.0
  README.md
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/commands/Help.java
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/commands/Invite.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Source.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/Badges.java
  src/main/java/de/chojo/repbot/config/elements/Database.java
  src/main/java/de/chojo/repbot/config/elements/Links.java
  src/main/java/de/chojo/repbot/config/elements/MagicImage.java
  src/main/java/de/chojo/repbot/config/elements/TestMode.java
  src/main/java/de/chojo/repbot/config/exception/ConfigurationException.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/updater/VersionInfo.java
  src/main/java/de/chojo/repbot/data/util/DbUtil.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildSettingUpdate.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationLogEntry.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationRole.java
  src/main/java/de/chojo/repbot/listener/LogListener.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/listener/voting/VoteRequest.java
  src/main/java/de/chojo/repbot/service/RepBotCachePolicy.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/java/de/chojo/repbot/util/Colors.java
  src/main/java/de/chojo/repbot/util/MessageUtil.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/version
Labels: enhancement

#70 Fix array out of bound exception when no ranks are present
  src/main/java/de/chojo/repbot/commands/TopReputation.java
Labels: bug, size: small

#71 Feature/botlist integration
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/Botlist.java
Labels: enhancement, size: small

#68 Check if bot can interact with roles when required
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/service/RoleAccessException.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: bug, enhancement, size: small

#73 Fix that last 10 messages were ignored when they were too old.
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
Labels: bug, size: small

#72 Feature/fix info
  .gitignore
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: bug, size: small

#75 Feature/bot owner actions
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/BaseSettings.java
  src/main/java/de/chojo/repbot/listener/InternalCommandListener.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
Labels: enhancement, size: medium

#74 Add error message when a permission is missing
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Help.java
  src/main/java/de/chojo/repbot/config/elements/Botlist.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, size: small

#76 Release of 1.2.1
  .gitignore
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/commands/Help.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/Badges.java
  src/main/java/de/chojo/repbot/config/elements/BaseSettings.java
  src/main/java/de/chojo/repbot/config/elements/Botlist.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/listener/InternalCommandListener.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/service/RoleAccessException.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/resources/database/1/patch_2.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement, size: medium

#77 Feature/analyzer rework
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/AnalyzerSettings.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/service/RepBotCachePolicy.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
Labels: enhancement, refactoring, size: small

#79 Implement fancy presence
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/PresenceSettings.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/StatisticData.java
  src/main/java/de/chojo/repbot/data/VoiceData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/listener/InternalCommandListener.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/service/PresenceService.java
  src/main/java/de/chojo/repbot/statistic/ReplacementProvider.java
  src/main/java/de/chojo/repbot/statistic/Statistic.java
  src/main/java/de/chojo/repbot/statistic/element/DataStatistic.java
  src/main/java/de/chojo/repbot/statistic/element/GlobalShardStatistic.java
  src/main/java/de/chojo/repbot/statistic/element/ProcessStatistics.java
  src/main/java/de/chojo/repbot/statistic/element/ShardStatistic.java
  src/main/java/de/chojo/repbot/statistic/element/SystemStatistics.java
  src/main/resources/Thankswords.json
  src/main/resources/database/1/patch_4.sql
Labels: feature, size: medium

#82 Add welcome message on guild join
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: enhancement

#80 Release of 1.2.3
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Help.java
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/commands/Invite.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/commands/TopReputation.java
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/AnalyzerSettings.java
  src/main/java/de/chojo/repbot/config/elements/Badges.java
  src/main/java/de/chojo/repbot/config/elements/BaseSettings.java
  src/main/java/de/chojo/repbot/config/elements/Botlist.java
  src/main/java/de/chojo/repbot/config/elements/Database.java
  src/main/java/de/chojo/repbot/config/elements/Links.java
  src/main/java/de/chojo/repbot/config/elements/MagicImage.java
  src/main/java/de/chojo/repbot/config/elements/PresenceSettings.java
  src/main/java/de/chojo/repbot/config/elements/TestMode.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/StatisticData.java
  src/main/java/de/chojo/repbot/data/VoiceData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/listener/InternalCommandListener.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/serialization/ThankwordsContainer.java
  src/main/java/de/chojo/repbot/service/PresenceService.java
  src/main/java/de/chojo/repbot/service/RepBotCachePolicy.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/statistic/EmbedDisplay.java
  src/main/java/de/chojo/repbot/statistic/ReplacementProvider.java
  src/main/java/de/chojo/repbot/statistic/Statistic.java
  src/main/java/de/chojo/repbot/statistic/display/GlobalInfoStatisticDisplay.java
  src/main/java/de/chojo/repbot/statistic/display/SystemInfoStatisticDisplay.java
  src/main/java/de/chojo/repbot/statistic/element/DataStatistic.java
  src/main/java/de/chojo/repbot/statistic/element/GlobalShardStatistic.java
  src/main/java/de/chojo/repbot/statistic/element/ProcessStatistics.java
  src/main/java/de/chojo/repbot/statistic/element/ShardCountStatistic.java
  src/main/java/de/chojo/repbot/statistic/element/ShardStatistic.java
  src/main/java/de/chojo/repbot/statistic/element/SystemStatistics.java
  src/main/resources/Thankswords.json
  src/main/resources/database/1/patch_3.sql
  src/main/resources/database/1/patch_4.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: bug, enhancement, feature

#89 Feature/gdpr
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Gdpr.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/data/GdprData.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/wrapper/RemovalTask.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/java/de/chojo/repbot/service/GdprService.java
  src/main/resources/database/1/patch_5.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: feature, size: medium

#90 Version 1.2.4
  README.md
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Gdpr.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/data/GdprData.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/updater/SqlUpdater.java
  src/main/java/de/chojo/repbot/data/wrapper/RemovalTask.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/java/de/chojo/repbot/listener/VoiceStateListener.java
  src/main/java/de/chojo/repbot/service/GdprService.java
  src/main/java/de/chojo/repbot/service/RepBotCachePolicy.java
  src/main/resources/database/1/patch_5.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
Labels: size: medium
