Repository rainbowdashlabs/reputation-bot, pull requests merged in 2022-04, with the labels that each got.

#232 Migration to latest cjda version
  .github/workflows/verify.yml
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/AbuseProtection.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Dashboard.java
  src/main/java/de/chojo/repbot/commands/Debug.java
  src/main/java/de/chojo/repbot/commands/Gdpr.java
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/commands/Invite.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/Prune.java
  src/main/java/de/chojo/repbot/commands/Reactions.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/commands/Top.java
  src/main/java/de/chojo/repbot/commands/TopMonth.java
  src/main/java/de/chojo/repbot/commands/TopWeek.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/java/de/chojo/repbot/statistic/EmbedDisplay.java
  src/main/java/de/chojo/repbot/statistic/ReplacementProvider.java
  src/main/java/de/chojo/repbot/util/Colors.java
  src/main/java/de/chojo/repbot/util/EmojiDebug.java
  src/main/java/de/chojo/repbot/util/LogNotify.java
  src/main/java/de/chojo/repbot/util/Messages.java
  src/main/java/de/chojo/repbot/util/PermissionErrorHandler.java
  src/main/java/de/chojo/repbot/util/Permissions.java
  src/main/java/de/chojo/repbot/util/StringUtil.java
  src/main/java/de/chojo/repbot/util/TextGenerator.java
Labels: dependencies

#237 Feature/localization enhancements
  src/main/java/de/chojo/repbot/commands/AbuseProtection.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prune.java
  src/main/java/de/chojo/repbot/commands/Reactions.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
  src/main/resources/locale_ru_RU.properties
Labels: enhancement, size: large

#239 Implement pagination for log command
  build.gradle.kts
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/wrapper/GuildRanking.java
  src/main/java/de/chojo/repbot/data/wrapper/PageAccess.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationLogAccess.java
  src/main/java/de/chojo/repbot/data/wrapper/ReputationLogEntry.java
Labels: enhancement, size: small

#244 Update requirements and instructions for selfhosting
  README.md
Labels: documentation

#246 Implement empty page handling
  build.gradle.kts
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Top.java
Labels: bug, size: small, prio: highest

#255 Fix/exception cleanup
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
Labels: bug, size: small

#256 Migrate gh pages to mkdocs
  .github/workflows/docs.yml
  docs/abuse_protection.md
  docs/commands.md
  docs/faq.md
  docs/give_reputation.md
  docs/index.md
  docs/invite.md
  docs/resources/answer.png
  docs/resources/embed.png
  docs/resources/fuzzy.png
  docs/resources/mention.png
  docs/resources/profile.png
  docs/resources/reaction.png
  docs/resources/roles.png
  docs/setup.md
  docs/tos-privacy.md
  mkdocs-setup
  mkdocs.yml
Labels: documentation, size: medium
