Repository rainbowdashlabs/reputation-bot, pull requests merged in 2022-11, with the labels that each got.

#434 Fix grammar of introduction
  README.md
Labels: documentation

#435 Fix user metrics not saved
  src/main/java/de/chojo/repbot/dao/access/metrics/Users.java
Labels: bug

#436 Add list type and some channels to channel debug
  src/main/java/de/chojo/repbot/commands/bot/handler/Debug.java
Labels: enhancement

#441 Enforce limits for number input
  src/main/java/de/chojo/repbot/commands/abuseprotection/AbuseProtection.java
  src/main/java/de/chojo/repbot/commands/repadmin/RepAdmin.java
  src/main/java/de/chojo/repbot/commands/roles/Roles.java
  src/main/java/de/chojo/repbot/commands/scan/Scan.java
Labels: enhancement

#449 Reorder receiver and donor commands
  src/main/java/de/chojo/repbot/commands/roles/Roles.java
  src/main/java/de/chojo/repbot/commands/roles/handler/donor/AddDonor.java
  src/main/java/de/chojo/repbot/commands/roles/handler/donor/RemoveDonor.java
  src/main/java/de/chojo/repbot/commands/roles/handler/receiver/AddReceiver.java
  src/main/java/de/chojo/repbot/commands/roles/handler/receiver/RemoveReceiver.java
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
Labels: enhancement

#453 Add log for reputation service
  build.gradle.kts
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/analyzer/results/AnalyzerResult.java
  src/main/java/de/chojo/repbot/analyzer/results/Result.java
  src/main/java/de/chojo/repbot/analyzer/results/empty/EmptyAnalyzerResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/AnswerAnalyzerResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/DirectAnalyzerResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/FuzzyAnalyzerResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/MatchAnalyzerResult.java
  src/main/java/de/chojo/repbot/commands/thankwords/handler/Check.java
  src/main/java/de/chojo/repbot/core/Bot.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/Analyzer.java
  src/main/java/de/chojo/repbot/dao/snapshots/AnalyzerTrace.java
  src/main/java/de/chojo/repbot/dao/snapshots/SubmitResultEntry.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/reputation/ReputationService.java
  src/main/java/de/chojo/repbot/service/reputation/SubmitResult.java
  src/main/java/de/chojo/repbot/service/reputation/SubmitResultType.java
  src/main/resources/database/postgresql/1/patch_25.sql
  src/main/resources/database/version
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
Labels: enhancement, size: large
