Repository rainbowdashlabs/reputation-bot, pull requests merged in 2022-10, with the labels that each got.

#414 Feature/reset date
  build.gradle.kts
  src/main/java/de/chojo/repbot/commands/repadmin/RepAdmin.java
  src/main/java/de/chojo/repbot/commands/repadmin/handler/resetdate/CurrentResetDate.java
  src/main/java/de/chojo/repbot/commands/repadmin/handler/resetdate/RemoveResetDate.java
  src/main/java/de/chojo/repbot/commands/repadmin/handler/resetdate/SetResetDate.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/Settings.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/General.java
  src/main/resources/database/postgresql/1/patch_23.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
  src/test/java/de/chojo/repbot/dataconsistency/TestLocalization.java
Labels: size: large, feature

#413 Feature/analyzer log
  src/main/java/de/chojo/repbot/analyzer/AnalyzerResult.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/analyzer/ThankType.java
  src/main/java/de/chojo/repbot/analyzer/results/Result.java
  src/main/java/de/chojo/repbot/analyzer/results/ResultType.java
  src/main/java/de/chojo/repbot/analyzer/results/empty/EmptyResult.java
  src/main/java/de/chojo/repbot/analyzer/results/empty/EmptyResultReason.java
  src/main/java/de/chojo/repbot/analyzer/results/match/AnswerResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/DirectResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/FuzzyResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/MatchResult.java
  src/main/java/de/chojo/repbot/analyzer/results/match/ThankType.java
  src/main/java/de/chojo/repbot/analyzer/results/match/fuzzy/MemberMatch.java
  src/main/java/de/chojo/repbot/commands/bot/handler/SharedGuilds.java
  src/main/java/de/chojo/repbot/commands/log/Log.java
  src/main/java/de/chojo/repbot/commands/log/handler/Analyzer.java
  src/main/java/de/chojo/repbot/commands/log/handler/LogFormatter.java
  src/main/java/de/chojo/repbot/commands/scan/util/ScanProcess.java
  src/main/java/de/chojo/repbot/commands/thankwords/handler/Check.java
  src/main/java/de/chojo/repbot/core/Bot.java
  src/main/java/de/chojo/repbot/core/Data.java
  src/main/java/de/chojo/repbot/dao/access/Analyzer.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/Reputation.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/Analyzer.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/RepUser.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/Thankwords.java
  src/main/java/de/chojo/repbot/dao/snapshots/ReputationLogEntry.java
  src/main/java/de/chojo/repbot/dao/snapshots/ResultEntry.java
  src/main/java/de/chojo/repbot/dao/snapshots/analyzer/ResultSnapshot.java
  src/main/java/de/chojo/repbot/dao/snapshots/analyzer/match/AnswerResultSnapshot.java
  src/main/java/de/chojo/repbot/dao/snapshots/analyzer/match/DirectResultSnapshot.java
  src/main/java/de/chojo/repbot/dao/snapshots/analyzer/match/FuzzyResultSnapshot.java
  src/main/java/de/chojo/repbot/dao/snapshots/analyzer/match/MatchResultSnapshot.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/AnalyzerService.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/resources/database/postgresql/1/patch_23.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
Labels: enhancement, size: very large, feature

#416 Fix wrong table name
  src/main/resources/database/postgresql/1/patch_23.sql
Labels: bug

#419 Add command to reload configuration
  src/main/java/de/chojo/repbot/commands/bot/BotAdmin.java
  src/main/java/de/chojo/repbot/commands/bot/handler/system/Reload.java
Labels: size: small, feature

#418 Refresh roles after reputation modification
  src/main/java/de/chojo/repbot/commands/repadmin/RepAdmin.java
  src/main/java/de/chojo/repbot/commands/repadmin/handler/reputation/Add.java
  src/main/java/de/chojo/repbot/commands/repadmin/handler/reputation/BaseReputationModifier.java
  src/main/java/de/chojo/repbot/commands/repadmin/handler/reputation/Remove.java
  src/main/java/de/chojo/repbot/commands/repadmin/handler/reputation/Set.java
  src/main/java/de/chojo/repbot/core/Bot.java
Labels: enhancement, size: small

#417 Feature/support voice text channel
  src/main/java/de/chojo/repbot/commands/channel/handler/BaseChannelModifier.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/Channels.java
Labels: enhancement, size: small

#424 Enhance metrics by freezing current states
  docs/metrics.md
  src/main/java/de/chojo/repbot/core/Bot.java
  src/main/java/de/chojo/repbot/dao/access/metrics/Reputation.java
  src/main/java/de/chojo/repbot/dao/access/metrics/Users.java
  src/main/java/de/chojo/repbot/service/MetricService.java
  src/main/java/de/chojo/repbot/web/routes/v1/metrics/Reputation.java
  src/main/resources/database/postgresql/1/patch_24.sql
  src/main/resources/database/version
Labels: enhancement, size: large

#420 Send gdpr data directly
  src/main/java/de/chojo/repbot/commands/gdpr/handler/Request.java
  src/main/java/de/chojo/repbot/dao/access/Gdpr.java
  src/main/java/de/chojo/repbot/dao/access/gdpr/GdprUser.java
  src/main/java/de/chojo/repbot/service/GdprService.java
  src/main/resources/database/postgresql/1/patch_24.sql
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
Labels: enhancement, size: small

#415 Replace fixed times for cleanup with config values
  src/main/java/de/chojo/repbot/config/ConfigFile.java
  src/main/java/de/chojo/repbot/config/Configuration.java
  src/main/java/de/chojo/repbot/config/elements/Cleanup.java
  src/main/java/de/chojo/repbot/core/Data.java
  src/main/java/de/chojo/repbot/dao/access/Analyzer.java
  src/main/java/de/chojo/repbot/dao/access/Gdpr.java
  src/main/java/de/chojo/repbot/dao/access/guild/Gdpr.java
  src/main/java/de/chojo/repbot/dao/access/guild/RepGuild.java
  src/main/java/de/chojo/repbot/dao/access/guild/RepGuildId.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/Reputation.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/RepUser.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/user/Gdpr.java
  src/main/java/de/chojo/repbot/dao/provider/Guilds.java
  src/main/java/de/chojo/repbot/dao/provider/Voice.java
  src/main/java/de/chojo/repbot/service/AnalyzerService.java
Labels: enhancement, size: medium

#432 Add missing tables to removal task
  src/main/java/de/chojo/repbot/dao/access/gdpr/RemovalTask.java
Labels: bug
