Repository rainbowdashlabs/reputation-bot, pull requests merged in 2022-09, with the labels that each got.

#387 Rewrite refresh mechanism
  src/main/java/de/chojo/repbot/commands/roles/handler/Refresh.java
  src/main/java/de/chojo/repbot/dao/snapshots/RepProfile.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
Labels: enhancement, size: small

#385 Feature/forum integration
  src/main/java/de/chojo/repbot/commands/channel/handler/Add.java
  src/main/java/de/chojo/repbot/commands/channel/handler/BaseChannelModifier.java
  src/main/java/de/chojo/repbot/commands/channel/handler/Remove.java
  src/main/java/de/chojo/repbot/commands/channel/handler/Set.java
  src/main/java/de/chojo/repbot/commands/setup/handler/Start.java
  src/main/java/de/chojo/repbot/core/Bot.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/Channels.java
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
  src/test/java/de/chojo/repbot/dataconsistency/TestLocalization.java
Labels: enhancement, size: medium

#395 Fix title localization for RepProfile
  src/main/java/de/chojo/repbot/dao/snapshots/RepProfile.java
Labels: bug, size: small

#397 Fix/announcement commands
  src/main/java/de/chojo/repbot/commands/channel/Channel.java
  src/main/java/de/chojo/repbot/commands/channel/handler/announcement/Channel.java
  src/main/java/de/chojo/repbot/commands/channel/handler/announcement/Location.java
  src/main/java/de/chojo/repbot/commands/channel/handler/announcement/Where.java
Labels: bug, size: small

#398 Fix several typos everywhere
  README.md
  docs/abuse_protection.md
  docs/commands.md
  docs/configuration.md
  docs/faq.md
  docs/give_reputation.md
  docs/hosting.md
  docs/index.md
  docs/invite.md
  docs/metrics.md
  docs/setup.md
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/dao/access/gdpr/GdprUser.java
  src/main/java/de/chojo/repbot/util/LogNotify.java
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_pt_BR.properties
Labels: documentation, size: small, locale

#400 Add bot admin commands for easier debugging
  build.gradle.kts
  src/main/java/de/chojo/repbot/commands/abuseprotection/AbuseProtection.java
  src/main/java/de/chojo/repbot/commands/abuseprotection/handler/MaxMessageReputation.java
  src/main/java/de/chojo/repbot/commands/bot/BotAdmin.java
  src/main/java/de/chojo/repbot/commands/bot/handler/Debug.java
  src/main/java/de/chojo/repbot/commands/bot/handler/Leave.java
  src/main/java/de/chojo/repbot/commands/bot/handler/Redeploy.java
  src/main/java/de/chojo/repbot/commands/bot/handler/Search.java
  src/main/java/de/chojo/repbot/commands/bot/handler/SharedGuilds.java
  src/main/java/de/chojo/repbot/commands/channel/Channel.java
  src/main/java/de/chojo/repbot/config/elements/BaseSettings.java
  src/main/java/de/chojo/repbot/core/Bot.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/AbuseProtection.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/General.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/Messages.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/Ranks.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/Reputation.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/RolesHolder.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/Thankwords.java
  src/main/java/de/chojo/repbot/dao/pagination/Announcements.java
  src/main/java/de/chojo/repbot/dao/snapshots/ReputationRank.java
  src/main/resources/locale.properties
  src/main/resources/locale_de.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr.properties
  src/main/resources/locale_pt_BR.properties
  src/main/resources/locale_ru.properties
Labels: size: large, feature

#401 Decomission internal command listener
  src/main/java/de/chojo/repbot/commands/bot/BotAdmin.java
  src/main/java/de/chojo/repbot/commands/bot/handler/SharedGuilds.java
  src/main/java/de/chojo/repbot/commands/bot/handler/system/Metrics.java
  src/main/java/de/chojo/repbot/commands/bot/handler/system/Restart.java
  src/main/java/de/chojo/repbot/commands/bot/handler/system/Shudown.java
  src/main/java/de/chojo/repbot/commands/bot/handler/system/Status.java
  src/main/java/de/chojo/repbot/commands/bot/handler/system/Upgrade.java
  src/main/java/de/chojo/repbot/config/elements/Api.java
  src/main/java/de/chojo/repbot/config/elements/BaseSettings.java
  src/main/java/de/chojo/repbot/core/Bot.java
  src/main/java/de/chojo/repbot/listener/InternalCommandListener.java
Labels: size: medium

#392 Feature/guild cleanup
  src/main/java/de/chojo/repbot/dao/access/guild/Cleanup.java
  src/main/java/de/chojo/repbot/dao/access/guild/Gdpr.java
  src/main/java/de/chojo/repbot/dao/access/guild/RepGuild.java
  src/main/java/de/chojo/repbot/dao/access/guild/RepGuildId.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/Reputation.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/Log.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/Ranking.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/Settings.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/AbuseProtection.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/General.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/Messages.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/Ranks.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/Reputation.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/Thanking.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/Channels.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/DonorRoles.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/Reactions.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/ReceiverRoles.java
  src/main/java/de/chojo/repbot/dao/access/guild/settings/sub/thanking/Thankwords.java
  src/main/java/de/chojo/repbot/dao/components/GuildHolder.java
  src/main/java/de/chojo/repbot/dao/components/MemberHolder.java
  src/main/java/de/chojo/repbot/dao/pagination/Announcements.java
  src/main/java/de/chojo/repbot/dao/pagination/GuildList.java
  src/main/java/de/chojo/repbot/dao/pagination/PageAccess.java
  src/main/java/de/chojo/repbot/dao/provider/Guilds.java
  src/main/java/de/chojo/repbot/dao/snapshots/ReputationRank.java
  src/main/java/de/chojo/repbot/service/GdprService.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/resources/database/postgresql/1/patch_23.sql
  src/main/resources/database/version
  src/test/java/de/chojo/repbot/dao/pagination/PageAccessTest.java
Labels: enhancement, size: medium
