Repository rainbowdashlabs/reputation-bot, pull requests merged in 2022-02, with the labels that each got.

#185 Fix exception for wrong channel type
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
Labels: bug, size: small

#186 Release 1.6.2
  build.gradle.kts
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
Labels: bug, size: small

#188 Update to JDA 5.0.0-alpha.5
  build.gradle.kts
  src/main/java/de/chojo/repbot/commands/AbuseProtection.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Dashboard.java
  src/main/java/de/chojo/repbot/commands/Gdpr.java
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/commands/Invite.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/Prune.java
  src/main/java/de/chojo/repbot/commands/Reactions.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/commands/Top.java
  src/main/java/de/chojo/repbot/commands/TopMonth.java
  src/main/java/de/chojo/repbot/commands/TopWeek.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/listener/voting/VoteComponent.java
  src/main/java/de/chojo/repbot/listener/voting/VoteRequest.java
  src/main/java/de/chojo/repbot/util/Permissions.java
Labels: dependencies

#189 Fix negative offset for Top commands
  build.gradle.kts
  src/main/java/de/chojo/repbot/commands/Top.java
  src/main/java/de/chojo/repbot/commands/TopMonth.java
  src/main/java/de/chojo/repbot/commands/TopWeek.java
Labels: bug

#191 Decouple permission apply for commands from welcome message
  src/main/java/de/chojo/repbot/listener/StateListener.java
Labels: enhancement

#192 Fix/some unhandled exceptions
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/util/Messages.java
Labels: bug
