Repository rainbowdashlabs/reputation-bot, pull requests merged in 2022-01, with the labels that each got.

#178 Migration to jda v5, threads, localized slash commands and permissions
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/commands/AbuseProtection.java
  src/main/java/de/chojo/repbot/commands/Channel.java
  src/main/java/de/chojo/repbot/commands/Dashboard.java
  src/main/java/de/chojo/repbot/commands/Gdpr.java
  src/main/java/de/chojo/repbot/commands/Help.java
  src/main/java/de/chojo/repbot/commands/Info.java
  src/main/java/de/chojo/repbot/commands/Invite.java
  src/main/java/de/chojo/repbot/commands/Locale.java
  src/main/java/de/chojo/repbot/commands/Log.java
  src/main/java/de/chojo/repbot/commands/Prefix.java
  src/main/java/de/chojo/repbot/commands/Prune.java
  src/main/java/de/chojo/repbot/commands/Reactions.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/java/de/chojo/repbot/commands/Reputation.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/commands/Scan.java
  src/main/java/de/chojo/repbot/commands/Setup.java
  src/main/java/de/chojo/repbot/commands/Thankwords.java
  src/main/java/de/chojo/repbot/commands/Top.java
  src/main/java/de/chojo/repbot/commands/TopMonth.java
  src/main/java/de/chojo/repbot/commands/TopWeek.java
  src/main/java/de/chojo/repbot/config/elements/SelfCleanup.java
  src/main/java/de/chojo/repbot/data/GuildData.java
  src/main/java/de/chojo/repbot/data/ReputationData.java
  src/main/java/de/chojo/repbot/data/wrapper/GeneralSettings.java
  src/main/java/de/chojo/repbot/data/wrapper/ThankSettings.java
  src/main/java/de/chojo/repbot/listener/InternalCommandListener.java
  src/main/java/de/chojo/repbot/listener/LegacyCommandListener.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/StateListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/java/de/chojo/repbot/service/SelfCleanupService.java
  src/main/java/de/chojo/repbot/statistic/Statistic.java
  src/main/java/de/chojo/repbot/statistic/element/ShardCountStatistic.java
  src/main/java/de/chojo/repbot/util/FilterUtil.java
  src/main/java/de/chojo/repbot/util/Messages.java
  src/main/java/de/chojo/repbot/util/PermissionErrorHandler.java
  src/main/java/de/chojo/repbot/util/Permissions.java
  src/main/resources/database/1/patch_16.sql
  src/main/resources/database/version
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
  src/main/resources/locale_ru_RU.properties
Labels: enhancement, size: very large, refactoring

#180 Add empty state for Top Command
  src/main/java/de/chojo/repbot/commands/Top.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
  src/main/resources/locale_ru_RU.properties
Labels: enhancement, size: small

#181 Fix/permissions
  build.gradle.kts
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/util/Guilds.java
  src/main/java/de/chojo/repbot/util/Permissions.java
Labels: bug

#183 Fix encoding a bit
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
Labels: help wanted
