Repository rainbowdashlabs/reputation-bot, pull requests merged in 2022-05, with the labels that each got.

#265 Fix exception in emoji usability check
  src/main/java/de/chojo/repbot/commands/Reactions.java
Labels: bug

#268 Fix/role update
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/Roles.java
  src/main/java/de/chojo/repbot/service/RepBotCachePolicy.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/java/de/chojo/repbot/util/Roles.java
Labels: enhancement

#277 Escape exception when max reaction are reached
  src/main/java/de/chojo/repbot/util/Messages.java
Labels: bug, size: small, prio: high

#275 Fix ignored min messages on message answer
  src/main/java/de/chojo/repbot/analyzer/AnalyzerResult.java
  src/main/java/de/chojo/repbot/analyzer/ContextResolver.java
  src/main/java/de/chojo/repbot/analyzer/MessageAnalyzer.java
  src/main/java/de/chojo/repbot/analyzer/MessageContext.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/Reputation.java
  src/main/java/de/chojo/repbot/dao/access/guild/reputation/sub/RepUser.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
  src/main/java/de/chojo/repbot/listener/ReactionListener.java
  src/main/java/de/chojo/repbot/listener/voting/ReputationVoteListener.java
  src/main/java/de/chojo/repbot/service/ReputationService.java
Labels: bug, size: medium, prio: high

#282 Fix failing deletion of a message
  src/main/java/de/chojo/repbot/dao/snapshots/ReputationLogEntry.java
Labels: bug

#286 Remove unused locale keys
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
  src/main/resources/locale_ru_RU.properties
Labels: refactoring, locale

#285 Feature/repsettings refactoring
  build.gradle.kts
  src/main/java/de/chojo/repbot/ReputationBot.java
  src/main/java/de/chojo/repbot/commands/RepSettings.java
  src/main/resources/locale.properties
  src/main/resources/locale_de_DE.properties
  src/main/resources/locale_en_US.properties
  src/main/resources/locale_es_ES.properties
  src/main/resources/locale_fr_FR.properties
  src/main/resources/locale_pt_PT.properties
  src/main/resources/locale_ru_RU.properties
Labels: enhancement

#288 Fix broken abuseprotection cooldown
  src/main/java/de/chojo/repbot/service/ReputationService.java
Labels: bug, prio: high

#290 Make MessageContext immutable
  src/main/java/de/chojo/repbot/analyzer/MessageContext.java
  src/main/java/de/chojo/repbot/listener/MessageListener.java
Labels: bug
