Repository rainbowdashlabs/reputation-bot, pull requests merged in 2023-01, with the labels that each got.

#471 Add given reputation to analyzer results
  src/main/java/de/chojo/repbot/commands/log/handler/Analyzer.java
Labels: enhancement

#473 Update wiki
  docs/abuse_protection.md
  docs/configuration.md
  docs/faq.md
  docs/give_reputation.md
  docs/hosting.md
  docs/index.md
Labels: documentation

#472 Fix ranking duplicates cause by missing offset aggregation
  src/main/resources/database/postgresql/1/patch_28.sql
  src/main/resources/database/version
Labels: bug

#475 Remove additional emojis on deletion
  src/main/java/de/chojo/repbot/listener/StateListener.java
Labels: bug

#478 Fix usage of setAllowedMentions and mention
  src/main/java/de/chojo/repbot/commands/roles/handler/List.java
  src/main/java/de/chojo/repbot/commands/roles/handler/donor/AddDonor.java
  src/main/java/de/chojo/repbot/commands/roles/handler/donor/RemoveDonor.java
  src/main/java/de/chojo/repbot/commands/roles/handler/receiver/AddReceiver.java
  src/main/java/de/chojo/repbot/commands/roles/handler/receiver/RemoveReceiver.java
  src/main/java/de/chojo/repbot/commands/setup/handler/Start.java
  src/main/java/de/chojo/repbot/service/RoleAssigner.java
  src/main/java/de/chojo/repbot/service/reputation/ReputationService.java
Labels: bug
